booker_app/config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/' => 'homes#top' ,as: 'root'

  get 'todolists/index' => 'todolists#index' ,as:'books'
  get 'todolists/:id' => 'todolists#show', as:'book'

  get 'todolists/:id/edit' => 'todolists#edit', as: 'edit_book'
  post 'todolists' => 'todolists#create'
  patch 'todolists/:id' => 'todolists#update', as: 'update_todolist'
  delete 'todolists/:id' => 'todolists#destroy', as:'destroy_todolist'



end

booker_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

booker_app/app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body,  presence: true
end

booker_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

booker_app/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end
end

booker_app/app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController



  def index
    @book = Book.new
    @books = Book.all
  end

 def create
    @book = Book.new(params_book)
    @books = Book.all
    if @book.save
      flash[:notice] = "successfully"
      redirect_to index_path

    else
      render "/todolists/index"
    end

end



  def show
    @book = Book.find(params[:id])

  end

  def edit
    @book = Book.find(params[:id])

  end
  def update

      @book=Book.find(params[:id])
      @book.update(params_book)
      if @book.save
          flash[:notice] = "successfully"
          redirect_to todolist_path
      else
          render :edit
      end

  end

  def destroy
      book = Book.find(params[:id])
      book.destroy
      redirect_to index_path

  end

  private

  def params_book
    params.require(:book).permit(:title, :body)
  end


end

booker_app/app/helpers/application_helper.rb
module ApplicationHelper
end

booker_app/app/helpers/homes_helper.rb
module HomesHelper
end

booker_app/app/helpers/todolists_helper.rb
module TodolistsHelper
end

booker_app/app/views/homes/top.html.erb
<div class="main">

  <h1 class="title">ようこそBookersへ！</h1>
  <div class="main">
    <p class="text">Bookersでは、さまざまな書籍に関するあなたの意見や</p>
    <p class="text">印象を共有し交換することができます。</p>

    <p class="start"><%=link_to "start",books_path%></p>
  </div>

booker_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

booker_app/app/views/todolists/edit.html.erb
<main>
  <h1>Editing Book</h1>

  <%= form_for(@book, url:"/todolists/#{@book.id}") do |f| %>

    <h4 class="title2">Title</h4>
    <%= f.text_field :title %>

    <h4 class="title2">Body</h4>
    <%= f.text_area :body %>
    <p class="update"><%= f.submit 'updatebook' %></p>

  <% end %>
  <%=link_to "show",edit_book_path %>
  <span class="dec">|</span>
  <%=link_to "back",book_path%>

  <% @book.errors.full_messages.each  do |message| %>
      <div class="form-error">
            <%= message %>
      </div>
  <%end%>

</main>

booker_app/app/views/todolists/index.html.erb
<main>
<h1 class="books">Books</h1>
<div class="main-clearfix">
<table>
  <div class ="title1">
    <tr>
      <td><h3 class="nav">title</h3></td>
      <td><h3 class="nav">Body</h3></td>
    </tr>
      <% @books.each do |book| %>
      <tr>
        <td><p class="text2"><%= book.title %></p></td>
        <td><p class="text2"><%= book.body %></p></td>
        <td>
          <p>
            <span class="link3"><%=link_to 'Show', book_path(book.id) %></span>
            <span class="link3"><%=link_to 'Edit', edit_book_path(book.id) %></span>
            <span class="link3"><%= link_to "Destroy", destroy_todolist_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></span>
          </p>
        </td>
      </tr>
      <%end%>

  </div>

  </table>


  </div>



<div class= "content">

  <h1>NEW BOOK </h1>
  <%=form_for(@book, url:'/todolists') do |f|%>

    <h4 class="title2">title</h4>
    <span><%=f.text_field :title %></span>

    <h4 class="title2">本文</h4>
    <span><%=f.text_area :body%></span>

    <%=f.submit 'create book'%>
  <%end%>
  <%=flash[:notice]%>


  <% @book.errors.full_messages.each  do |message| %>
      <div class="form-error">
            <%= message %>
      </div>
  <%end%>



 </div>
</main>

booker_app/app/views/todolists/show.html.erb
<main>
  <div class="title2">
    <span class="title3">title:<%= @book.title %></span>

  </div>
  <div class="title2">
    <span class=title3>Body:<%= @book.body %></span>


  </div>
    <div class="title2">
      <%=link_to "edit",edit_book_path %>
      |
      <%=link_to "back",books_path%>
    </div>
    <%=flash[:notice]%>

</main>